---
# tasks file for asquarezone.apache
- name: Install apache on debian
  apt:
    name: "{{apache_package_deb}}"
    state: present
  when: ansible_os_family == "Debian"
- name: Install apache on redhat
  yum:
    name: "{{apache_package_rhel}}"
    state: present
  when: ansible_os_family == "RedHat"
- name: Set services name for debina
  set_fact:
    apache_package: "{{apache_package_deb}}"
  when: ansible_os_family == "Debian"
- name: set service name for redhat
  set_fact:
    apache_package: "{{apache_package_rhel}}"
  when: ansible_os_family == "RedHat"
- name: service enable and start
  service:
    name: "{{apache_package}}"
    enabled: yes
    state: started
- name: test by print
  debug:
    msg: firing notification for redhat
  notify: restart rhel apache
  when: ansible_os_family == "RedHat"
                